### PR TITLE
Fix wincat to correctly detect when to interrupt/disconnect

### PR DESCRIPTION
**Pull request by benmoss**
Previously wasn't closing if the server disconnected, which was causing
e2e tests to fail.

https://github.com/kubernetes/kubernetes/issues/78857

@PatrickLang

### CODE REVIEW

**Comment by benmoss** [comment]
The e2e tests (under `--ginkgo.focus="Kubectl Port forwarding"`) are all passing for me after adding this wincat to my pause image.

**Comment by benmoss** [comment]
@bclau if you're interested in trying this out on your cluster too that'd be helpful

**Comment by neolit123** [comment]
@benmoss the cla bot is complaining about `gab-satchi needs CLA`
you might have to re-write the commit to include only you as author. the alterntive is for `gab-satchi` to get membership.

**Comment by bclau** [comment]
So, I've tried this new version wincat (built at ``claudiubelu/wincat:1.0``). It seems that this fixes the following tests (corresponding to the 1st case):

    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on 0.0.0.0 [k8s.io] that expects a client request should support a client that connects, sends DATA, and disconnects
    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects a client request should support a client that connects, sends DATA, and disconnects

but, the tests corresponding to the 2nd case (the one that hangs) are still not working, the issue still persists:

    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on localhost [k8s.io] that expects NO client request should support a client that connects, sends DATA, and disconnects
    [sig-cli] Kubectl Port forwarding [k8s.io] With a server listening on 0.0.0.0 [k8s.io] that expects NO client request should support a client that connects, sends DATA, and disconnects

**Comment by PatrickLang** [comment]
/lgtm

I talked to Claudiu and he thinks it's ok to merge. @bclau can you open an issue for the 2 remaining failures?

**Comment by bclau** [comment]
> 
> 
> /lgtm
> 
> I talked to Claudiu and he thinks it's ok to merge. @bclau can you open an issue for the 2 remaining failures?

Done: https://github.com/kubernetes-sigs/sig-windows-tools/issues/5

**Pull request merged**
