### PR TITLE
Added missing env variables for flannel and kube-proxy hostprocess

### LINKED ISSUE #264: Environment variables missing in flannel hostprocess daemon sets
**Describe the bug**
I completly followed [this guide](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md) you worked much on in the last days for Kubernetes 1.26.0. Both, flannel and kube-proxy, fails due to missing environment variables:
- flannel is missing `CNI_BIN_PATH` and `CNI_CONFIG_PATH` which results into this error message:
  ```
  PS C:\Users\kleonhardt> kubectl.exe logs -n kube-system    kube-flannel-ds-windows-amd64-7bdn7
  Copying SDN CNI binaries to host
  mkdir : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
  In C:\C\6ae19dcaa5f1c0fc4fd8fe97ab883d45dd1922d34377b7452d88be23ec466044\flannel\start.ps1:5 Zeichen:14
  + mkdir -force $env:CNI_BIN_PATH
  +              ~~~~~~~~~~~~~~~~~
      + CategoryInfo          : InvalidData: (:) [mkdir], ParentContainsErrorRecordException
      + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,mkdir
  ```
- kube-proxy is missing `CNI_BIN_PATH` which would result in a similar error

When setting `CNI_BIN_PATH` to `C:\opt\cni\bin` and `CNI_CONFIG_PATH` to `C:\etc\cni\net.d` this generally works.

@fabi200123 Maybe you can help quickly here :).
Thanks in advance.

Note: After setting these env variables I get another error which I already mentioned in another issue/pull request.
The error is:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8249f8c9d4845a1cfda66c0bc5becd7d035d3250c63a79e283a7352a3c8d6156": plugin type="flannel" name="flannel.4096" failed (add): incompatible CNI versions; config is "0.3.1", plugin supports ["0.2.0"]
```
I'm going to create a new real issue to follow that problem though.

**To Reproduce**
Just follow the guide to add a (new) windows node: https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md

**Expected behavior**
Flannel and kube-proxy should start without any erros.

**Kubernetes (please complete the following information):**
 - Windows Server version: Windows Server 2022 (21H2, Build 20348.1366)
 - Kubernetes Version: 1.26.0
 - CNI: flannel

### PR DESCRIPTION
**Pull request by Mik4sa**
**Reason for PR**:
Adds the missing env vars mentioned in #264

**Issue Fixed**:

Fixes #264

**Requirements**

- [ ] Sqaush commits 
- [ ] Documentation
- [ ] Tests

**Notes**:

### CODE REVIEW

**Comment by fabi200123** [comment]
@Mik4sa if you can, update the cniVersion from 0.3.1 to 0.2.0 in here too.

**Comment by Mik4sa** [comment]
I thought about multiple PRs to better follow the issues I created.

**Review by fabi200123 — APPROVED** [review]
/lgtm

**Pull request merged**
