### PR TITLE
Allow to password contains special symbols

### PR DESCRIPTION
**Pull request by vitaliy-leschenko**
**Issue Fixed**:
Currently we have a problem with actions that failed because docker-hub password contains special symbols.
This is fix for it.

### CODE REVIEW

**Comment by vitaliy-leschenko** [comment]
Ups... how to fix it?
image

**Comment by jsturtevant** [comment]
@vitaliy-leschenko labeler fix: https://github.com/kubernetes-sigs/sig-windows-tools/pull/135/files

**Comment by vitaliy-leschenko** [comment]
Now we need to re-release v0.1.5 because it broken.

**Comment by jsturtevant** [comment]
in progress...

**Comment by vitaliy-leschenko** [comment]
@jsturtevant thank you and sorry for my mistake.

**Comment by jsturtevant** [comment]
no problem.  We have images published `sigwindowstools/flannel:v0.13.0-nanoserver` :tada:

**Comment by jsturtevant** [comment]
The kube-proxy images will run a build tonight. Unfortunately github actions doesn't let me do a manual trigger of the scheduled job

**Comment by jsturtevant** [comment]
kubeproxy is now avaliable: `sigwindowstools/kube-proxy:v1.20.0-nanoserver`

**Pull request merged**
