### PR TITLE
Removing SAC releases from non-hostprocess images

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

**Reason for PR**:

All Windows SAC releases are deprecated.

**Issue Fixed**:

Issue #

**Requirements**

- [ ] Sqaush commits 
- [ ] Documentation
- [ ] Tests

**Notes**:

### CODE REVIEW

**Comment by marosset** [comment]
@Mik4sa @luxzeitlos Can you confirm the flannel versions listed here https://github.com/kubernetes-sigs/sig-windows-tools/pull/253/files#diff-4d02f62c685404f9d85bd0990da216c59e873afd1632abb44adb177ff10268c1L2-L6 work for you?

**Comment by marosset** [comment]
Related to https://github.com/kubernetes-sigs/sig-windows-tools/issues/251

**Comment by Mik4sa** [comment]
Back then I tested "nanoserver-ltsc2022" for Windows Server 2022. That's the reason I added it with #205 :)

**Comment by Mik4sa** [comment]
@marosset May you get this done by next week? In about one or two weeks I may need this for production and I would like to use the official images :)

**Comment by marosset** [comment]
> @marosset May you get this done by next week? In about one or two weeks I may need this for production and I would like to use the official images :)

@mik4sa I was waiting for your confirmation that the flannel versions are correct.
Once you confirm I can merge this right away.

**Comment by Mik4sa** [comment]
@marosset My bad. Back then I tested successfully flannel version 0.13.0 with kube-proxy for k8s 1.23.3

**Comment by jsturtevant** [comment]
@Mik4sa note these are published to docker hub and are subject to docker hubs rate limiting. Typically, we see customer want to have an image in their own registry for control and stability.  Another thing to note is these images only work with Dockershim which has been removed from k8s 1.23, they won't work well with containerd.

**Pull request merged**
