### PR TITLE
Use most recent kube proxy.yml

### LINKED ISSUE #267: Back-off pulling image "sigwindowstools/kube-proxy:VERSION-nanoserver"
**Describe the bug**
Following [this guide](https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md) for Kubernetes 1.26.0 and having fixed/considered #264 and #266 I now get an error while pulling the image for kube-proxy. The referenced command is `curl -L https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/kube-proxy.yml | sed 's/KUBE_PROXY_VERSION/v1.25.3/g' | kubectl apply -f -` which seems wrong to me. Note that I used `1.26.0` and not `1.25.3`.
The error I get is:
```
Back-off pulling image "sigwindowstools/kube-proxy:VERSION-nanoserver"
```

The reason here is that the yml file uses the following image: `image: sigwindowstools/kube-proxy:VERSION-nanoserver`. So the sed command should use `VERSION` instead of `KUBE_PROXY_VERSION`. Though I don't think that this is the issue here, since this didn't really worked for me aswell and I got others errors. Also, this isn't the most recent version of that file.

For my test I used the current file in master. So I executed this command:
`curl -L https://raw.githubusercontent.com/kubernetes-sigs/sig-windows-tools/master/hostprocess/flannel/kube-proxy/kube-proxy.yml | sed 's/KUBE_PROXY_VERSION/v1.26.0/g' | kubectl apply -f -`

This worked and I was finally able to deploy a pod to my windows node without any errors.

**To Reproduce**
Just follow the guide to add a (new) windows node: https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/guides/guide-for-adding-windows-node.md

**Expected behavior**
kube-proxy should start without any erros.

**Kubernetes (please complete the following information):**
 - Windows Server version: Windows Server 2022 (21H2, Build 20348.1366)
 - Kubernetes Version: 1.26.0
 - CNI: flannel

### PR DESCRIPTION
**Pull request by Mik4sa**
**Reason for PR**:
References the most recent kube-proxy.yml in the guide for adding windows node which was needed to successfully add one.

**Issue Fixed**:

Fixes #267  

**Requirements**

- [ ] Sqaush commits 
- [ ] Documentation
- [ ] Tests

**Notes**:

### CODE REVIEW

**Comment by jsturtevant** [comment]
could drop the commits that adds the same values as #265 and #268 ?

**Comment by Mik4sa** [comment]
Done. Thanks for noting :)

**Comment by jsturtevant** [comment]
@Mik4sa thanks for the fixes!

**Pull request merged**
