### PR TITLE
bug: pause image shouldn't emit logs

### PR DESCRIPTION
**Pull request by PatrickLang**
Fixes https://github.com/kubernetes/kubernetes/issues/81298

(also includes #4 for testing)

### CODE REVIEW

**Comment by PatrickLang** [comment]
@yujuhong - can you give this a look?

**Comment by yujuhong** [comment]
Changing to pauseloop lgtm. Thanks!

**Comment by benmoss** [comment]
if you wanted to go even further and reduce the memory footprnit you could use the pause.c code from https://github.com/kubernetes/kubernetes/pull/75618/files

**Pull request closed without merging**
